channels:
  - defaults
dependencies:
  - attrs
  - black
  - click
  - dask
  - flake8
  - isort
  - make
  - nomkl
  - mypy
  - numpy
  - pip
  - python=3.9.7
  - pytest
  - pytest-cov
  - xarray
  - pip:
    - mdformat-gfm
    - rioxarray
    - xarray-sentinel
