channels:
  - defaults
  - conda-forge
dependencies:
  - attrs
  - black
  - click
  - dask
  - flake8
  - isort
  - make
  - mdformat
  - mypy = 0.812
  - nomkl
  - numpy >= 1.20.0
  - pip
  - python=3.9.7
  - pytest
  - pytest-cov
  - rioxarray
  - xarray
  - xmlschema
  - pip:
    - mdformat-gfm
    - xarray-sentinel
