channels:
- conda-forge
dependencies:
- attrs
- bottleneck
- click
- dask == 2021.4.0
- flox
- fsspec
- make
- mdformat
- mypy
- nomkl
- numexpr
- numpy == 1.21.0
- pandas == 1.2.0
- pip
- pytest
- pytest-cov
- rasterio == 1.2.4
- rioxarray
- scipy
- typer
- types-setuptools
- xarray == 2022.06.0
- xarray-sentinel == 0.9.2
- xmlschema
- pip:
  - mdformat-gfm
