channels:
  - conda-forge
dependencies:
  - adlfs
  - build
  - gcsfs
  - gdal
  - matplotlib
  - mamba
  - notebook
  - pip
  - planetary-computer
  - proj-data
  - sentinelsat
  - stackstac
  - pip:
      - elevation
